import "./globals.css";
import Client from "./client";
import NaveBar from "../app/components/navebar/naveBar.jsx";
import liberationSans from "next/font/local";
import ginto from "next/font/local";
import manropeSans from "next/font/local";
import tajawal from "next/font/local";

const LiberationSansFont = liberationSans({
  src: "./fonts/liberation_sans/LiberationSans-Regular.ttf",
  variable: "--font-liberation-sans",
});

const GintoFont = ginto({
  src: "./fonts/ginto/ABCGintoNormal-Regular-Trial-BF651b7b7846685.otf",
  variable: "--font-ginto",
});

const ManropeSansFont = manropeSans({
  src: "./fonts/manrope/manrope-medium.otf",
  variable: "--font-manrope-sans",
});

const TajawalFont = tajawal({
  src: "./fonts/tajawal/Tajawal-Medium.ttf",
  variable: "--font-tajawal",
});

export const metadata = {
  title: "Bots-Buddies",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${LiberationSansFont.variable} ${GintoFont.variable} ${ManropeSansFont.variable} ${TajawalFont.variable}`}
    >
      <body cz-shortcut-listen="true" className="antialiased">
        <NaveBar />
        <Client>{children}</Client>
      </body>
    </html>
  );
}
